### PR TITLE
Fix for multiple pafs with references that are also assemblies

### PR DESCRIPTION
**Pull request by fubar2**
@bgruening - sorry to distrurb again but some fixes for a bug exposed by multiple paf tracks where references common to multiple tracks causing JB2 to complain. 

Probably easier to just replace the entire py to save merging manually - added a flag to control useful debugging of command line output - turn off for production since it's really useful right now and helped find that bug I just fixed.

XML is less trouble - has a change in the paf reference generating and some changed test assertions again - to match simplified track names without redundant ext being added and added session name from advanced options to the history output label.

### CODE REVIEW

**Comment by bgruening** [comment]
Cool, can you add a test?

**Comment by fubar2** [comment]
Just needs another paf file so yes - but cooking...

**Comment by fubar2** [comment]
Dinner was delicious. Hear's your test - a 2 way paf track added that reuses some other references.
Plus a few more assertions. Please, make a PR before I find more horrible deep bugs.

**Review by bgruening — APPROVED** [review]
Thanks!

**Comment by bgruening** [comment]
upps sorry.

**Pull request merged**
