### PR TITLE
add zip so biocontainer testing works. Not related but conda on EU update to 2.11.0 JB2 appears broken?

### PR DESCRIPTION
**Pull request by fubar2**
@bgruening - on EU with the latest JB2 `_16` it's failing - ?missing jb2 installation?:
Did the conda build work ok? It worked for me...

EU bug report shows:

```
which: no jbrowse in (/usr/local/tools/_cache/5d44bb7d/bin:/usr/local/tools/_conda/condabin:/opt/galaxy/venv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin) dirname: missing operand
Try 'dirname --help' for more information.
Traceback (most recent call last):
  File "/opt/galaxy/custom-tools/jbrowse2/autogenJB2.py", line 62, in <module>
    jc = jbC(
         ^^^^
  File "/opt/galaxy/custom-tools/jbrowse2/jbrowse2.py", line 420, in __init__
    self.clone_jbrowse()
  File "/opt/galaxy/custom-tools/jbrowse2/jbrowse2.py", line 1538, in clone_jbrowse
    shutil.copytree(self.jbrowse2path, dest, dirs_exist_ok=True)
  File "/usr/local/tools/_cache/5d44bb7d/lib/python3.12/shutil.py", line 586, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/../opt/jbrowse2'
```

Works fine here.
A minor issue fixed by this PR: zip is now needed as a dependency for 2.11.0 it seems as otherwise the test fails when using ```--biocontainers```

### CODE REVIEW

**Comment by bgruening** [comment]
Should we add zip to the bioconda package? E.g. is it a dependency of jbrowse2 or Galaxy?

**Comment by fubar2** [comment]
> Should we add zip to the bioconda package? E.g. is it a dependency of jbrowse2 or Galaxy?
It's already in this packages deps but the biocontainer may not have been updated. 
Last time I tried --biocontainers, tests passed. I'll double check but i don't think anything has changed.

**Comment by fubar2** [comment]
It runs fine on EU so presumably the biocontainer works!

**Comment by fubar2** [comment]
oh - i forgot it's a "special case" so conda. Ah. Interesting.

**Comment by fubar2** [comment]
looks like it's updated already in https://github.com/BioContainers/multi-package-containers/blob/master/combinations/hash.tsv ?

>jbrowse2=2.11.0,biopython=1.82,bcbio-gff=0.7.1,samtools=1.19,pyyaml=6.0.1,tabix=1.11,findutils=4.6.0,hictk=0.0.12-0,zip=3.0	bioconda/base-glibc-busybox-bash-fake-user:3.0	0

**Comment by fubar2** [comment]
@bgruening: emergency problem with failed conda installation **again**:
which: no jbrowse in (/usr/local/tools/_cache/5d44bb7d/bin:/usr/local/tools/_conda/condabin:/opt/galaxy/venv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin)
dirname: missing operand
Try 'dirname --help' for more information.
Traceback (most recent call last):
  File "/opt/galaxy/custom-tools/jbrowse2/jbrowse2.py", line 1580, in <module>
    jc = JbrowseConnector(outdir=args.outdir, jbrowse2path=args.jbrowse2path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/galaxy/custom-tools/jbrowse2/jbrowse2.py", line 420, in __init__
    self.clone_jbrowse()
  File "/opt/galaxy/custom-tools/jbrowse2/jbrowse2.py", line 1538, in clone_jbrowse
    shutil.copytree(self.jbrowse2path, dest, dirs_exist_ok=True)
  File "/usr/local/tools/_cache/5d44bb7d/lib/python3.12/shutil.py", line 586, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/../opt/jbrowse2'

**Pull request merged**
