### PR TITLE
fixes for pafs with multiple shared references

### PR DESCRIPTION
**Pull request by fubar2**
paf fixes needed for multiple pafs with shared references
add` min=1 `for paf reference repeat inputs

### CODE REVIEW

**Comment by fubar2** [comment]
@bgruening - need these patches on your rebased tools-iuc fork - what's the easiest way? 
Working on my own fork so cannot figure out how to make a PR for yours safely?

**Comment by bgruening** [comment]
Single commit would be the easiest way for me.

**Comment by fubar2** [comment]
@bgruening Need this to fix treevalgal workflows on EU for now - the pafs are broken at present :( 
Might be more to come. Tell me what to do?

**Comment by bgruening** [comment]
I will deal with it

**Comment by bgruening** [comment]
🐰🐣🐰 happy Easter

**Comment by fubar2** [comment]
@bgruening - thanks. Will test tomorrow. There will be plenty more to merge I'm sure.

**Pull request merged**
